{
  "code": "def find(num1, num2):\n    try:\n        return num1 // num2\n    except ZeroDivisionError:\n        return \"Error: Division by zero is not allowed.\"\n",
  "results": {
    "assert find(10,3) == 3": {
      "result": true,
      "time": 0.33224964141845703,
      "error": null
    },
    "assert find(4,2) == 2": {
      "result": true,
      "time": 0.29093217849731445,
      "error": null
    },
    "assert find(20,5) == 4": {
      "result": true,
      "time": 0.28021764755249023,
      "error": null
    }
  },
  "passed": true,
  "accuracy": 1.0,
  "general_error": null,
  "has_testcase_error": false
}