{
  "code": "def find_last_occurrence(arr, num):\n    try:\n        return len(arr) - 1 - arr[::-1].index(num)\n    except ValueError:\n        return \"Number not found in the array\"\n",
  "results": {
    "assert find_last_occurrence([2, 5, 5, 5, 6, 6, 8, 9, 9, 9], 5) == 3": {
      "result": true,
      "time": 0.17309141159057617,
      "error": null
    },
    "assert find_last_occurrence([2, 3, 5, 8, 6, 6, 8, 9, 9, 9], 9) == 9": {
      "result": true,
      "time": 0.5289607048034668,
      "error": null
    },
    "assert find_last_occurrence([2, 2, 1, 5, 6, 6, 6, 9, 9, 9], 6) == 6": {
      "result": true,
      "time": 0.17814254760742188,
      "error": null
    }
  },
  "passed": true,
  "accuracy": 1.0,
  "general_error": null,
  "has_testcase_error": false
}